cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'
tap 'homebrew/cask-fonts'

brew 'awscli'
brew 'ack'
brew 'coreutils'
brew 'grc'
brew 'gettext'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'puma/puma/puma-dev'
brew 'pyenv'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'tmux'
brew 'unrar'
brew 'nvim'
brew 'wget'
brew 'yarn'

cask '1password'
cask 'alfred'
cask 'docker'
cask 'docker-toolbox'
cask 'font-fira-code'
cask 'graphiql'
cask 'iterm2'
cask 'slack'
cask 'transmit'
cask 'vlc'
