cask_args appdir: '/Applications'

tap 'homebrew/bundle'

cask '1password-cli'
brew 'bash'
brew 'bash-completion@2'
brew 'git'
brew 'gh'
brew 'ack'
brew 'coreutils'
brew 'gettext'
brew 'kubernetes-cli'
brew 'colima'
brew 'openssl@3'
brew 'readline'
brew 'pipx'
brew 'pyenv'
brew 'rsync'
brew 'roundup'
brew 'tmux'
brew 'wget'
