alias k='kubectl'
alias ka='kubectl apply -f'
alias kd='kubectl delete'
alias kdp='kubectl describe pods'
alias ke='kubectl exec -it'
alias kg='kubectl get'
alias kga='kubectl get --all-namespaces all'
alias kgd='kubectl get deployments'
alias kgi='kubectl get ingress'
alias kgp='kubectl get pods'
alias kgs='kubectl get secrets'
alias kgsvc='kubectl get service'
alias kl='kubectl logs --tail=100 -f'
alias krm='kubectl delete'
alias devkube='kubectl config use-context minikube'
