alias k='kubectl'
alias kd='kubectl delete'
alias kg='kubectl get'
alias ka='kubectl apply -f'
alias kl='kubectl logs --tail=100 -f'
alias kgp='kubectl get pods'
alias kgs='kubectl get secrets'
alias kgsvc='kubectl get service'
alias kgd='kubectl get deployments'
alias kdp='kubectl describe pods'
alias kgi='kubectl get ingress'
alias devkube='kubectl config use-context minikube'
